---
language: python
python: "2.7"

env:
  - TOX_ENV=py27

services:
  - docker

before_install:
  - docker --version
  - docker info
  - export GALAXY_HOME=/home/galaxy
  - export GALAXY_TRAVIS_USER=galaxy
  - export GALAXY_UID=1450
  - export GALAXY_GID=1450
  - sudo groupadd -r $GALAXY_TRAVIS_USER -g $GALAXY_GID
  - sudo useradd -u $GALAXY_UID -r -g $GALAXY_TRAVIS_USER -d $GALAXY_HOME -p travis_testing -c "Galaxy user" $GALAXY_TRAVIS_USER
  - sudo mkdir $GALAXY_HOME
  - sudo chown -R $GALAXY_TRAVIS_USER:$GALAXY_TRAVIS_USER $GALAXY_HOME

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

  # download the Galaxy Docker image and build it to test the playrole
  - mkdir $HOME/galaxy-docker
  - wget -q -O - https://github.com/bgruening/docker-galaxy-stable/archive/master.tar.gz | tar xzf - --strip-components=1 -C $HOME/galaxy-docker
  # remove the submodule role
  - rm $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/* -rf
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile -O $HOME/galaxy-docker/Makefile
  # install BioBlend
  - make install -f $HOME/galaxy-docker/Makefile

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i "localhost," tests/syntax.yml --syntax-check
  # Copy the ansible-playbook from this repo into the Docker roles directory and build the image.
  - cp -r ./* $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - ls -l $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - cd $HOME/galaxy-docker/ && docker build -t galaxy-docker/test ./galaxy/
  # run various tests against the container
  - make docker_run
  - sleep 30
  - make test_api
  - make test_ftp
  - make test_bioblend
  - make test_docker_in_docker
