---
# file: local.yml
#   Short-cut to run local install tasks without setting up an inventory.
#
# Run roles locally via following command:
#   ansible-playbook -i localhost, local.yml [-e var=val]* --tags=<tag[,tag]> --skip-tags=<tag[,tag]>
- hosts: localhost
  connection: local
  tasks:
  - include: tasks/slurm.yml
    tags: slurm
  - include: tasks/pbs.yml
    tags: pbs
  - include: tasks/nginx.yml
    tags: nginx
  - include: tasks/proftpd.yml
    tags: proftpd
  - include: tasks/supervisor.yml
    tags: supervisor

