- name: "Install most of the conditional dependencies"
  # https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/conditional-requirements.txt
  pip:
    name: "{{item}}"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    extra_args: --index-url https://wheels.galaxyproject.org/simple --extra-index-url https://pypi.python.org/simple
  become: True
  become_user: "{{ galaxy_user_name }}"
  with_items:
    - "psycopg2-binary==2.7.7"
    - "weberror==0.10.3"
    - "python-openid"
    - "fluent-logger"
    - "raven"
    - "drmaa"
    - "statsd"
    - "graphitesend"
    - "python-ldap==2.4.44"
    - "pykube==0.15.0"
    - "kamaki"
    - "azure-storage==0.32.0"
