
- assert:
    that:
      - globus_username is defined
      - globus_passwd is defined

# http://docs.ansible.com/ansible/get_url_module.html
- name: Download Globus Connect Server
  shell: curl -LOs http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo_latest_all.deb
  become: true

- name: Install Globus Repo
  shell: dpkg -i globus-connect-server-repo_latest_all.deb
  become: true

- name: apt update
  apt: update_cache=yes
  become: true

- name: Install Globus Connect Server
  apt: pkg=globus-connect-server
  become: true

- name: test
  shell: echo {{ ansible_hostname }}  > test1.tmp

- template: src=templatesglobus.conf dest=/etc/globus.conf

- expect:
  command: globus-connect-server-setup
  responses:
    (?i)Globus Username: "{{ globus_username }}"
    (?i)Globus Password: "{{ globus_passwd }}"
