- name: "Install gravity for galaxy"
  pip: 
    name: gravity
    version: 1.0.6
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.python.org/simple"
  become: True
  become_user: "{{ galaxy_user_name }}"
  when: galaxy_extras_install_packages

- name: Deploy galaxyctl wrapper script
  copy:
    content: |
      #!/usr/bin/env sh
      export GRAVITY_CONFIG_FILE={{ gravity_config_file }}
      export GRAVITY_STATE_DIR={{ gravity_state_dir }}
      exec sudo -E -u $GALAXY_USER {{ galaxy_venv_dir }}/bin/galaxyctl "$@"
    dest: "/usr/local/bin/galaxyctl"
    mode: "0755"
  become: True
  become_user: root

- name: "Install Gravity conf"
  template: src=gravity.yml.j2 dest={{ gravity_config_file }} owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
