
# letsencrypt_setup must have been turned on

csr_country: "US"
csr_locality: "New York"
csr_organization: "Your company"
csr_state: "New York"
csr_common_name: "{{ansible_fqdn}}"
csr_days: "365"
csr_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

- name: Generate CSR
  command: openssl req -new -sha256 -subj "{{ csr_fields }}" -key /etc/pki/cert/private/account.key -out /etc/pki/cert/csr/sample.com.csr
    creates: /etc/pki/cert/csr/sample.com.csr


- letsencrypt:
    account_key: /etc/pki/cert/private/account.key
    csr: /etc/pki/cert/csr/sample.com.csr
    dest: /etc/httpd/ssl/sample.com.crt
  register: sample_com_challenge

- debug: msg="csr submitted, sample challenge registered"
  when: sample_com_challenge|changed

- copy:
    dest: /var/www/html/{{ sample_com_challenge['challenge_data']['sample.com']['http-01']['resource'] }}
    content: "{{ sample_com_challenge['challenge_data']['sample.com']['http-01']['resource_value'] }}"
  when: sample_com_challenge|changed

- letsencrypt:
    account_key: /etc/pki/cert/private/account.key
    csr: /etc/pki/cert/csr/sample.com.csr
    dest: /etc/httpd/ssl/sample.com.crt
    data: "{{ sample_com_challenge }}"
  when: sample_com_challenge|changed

