
- include_tasks: galaxy_root.yml
  when: galaxy_extras_config_galaxy_root | bool
  tags:
   - galaxy

- name: Create directory for "galaxy_config_dir"
  file: path="{{ galaxy_config_dir }}" state=directory

- include_tasks: galaxy_metrics.yml
  when: galaxy_extras_config_galaxy_root | bool
  tags:
   - metrics

- include_tasks: galaxy_extra_dependencies.yml
  when: galaxy_extras_config_galaxy_extra_dependencies | bool
  tags:
   - extra_dependencies

- include_tasks: gravity.yml
  when: galaxy_extras_config_gravity | bool
  tags:
   - gravity

- include_tasks: nginx.yml
  when: galaxy_extras_config_nginx | bool
  tags:
   - nginx_config
   - nginx

- include_tasks: proftpd.yml
  when: galaxy_extras_config_proftpd | bool
  tags:
   - proftpd

- include_tasks: slurm.yml
  when: galaxy_extras_config_slurm | bool
  tags:
   - slurm

- include_tasks: pbs.yml
  when: galaxy_extras_config_pbs | bool
  tags:
   - pbs

- include_tasks: k8s.yml
  when: galaxy_extras_config_k8s_jobs | bool
  tags:
   - k8s

- include_tasks: condor.yml
  when: galaxy_extras_config_condor | bool
  tags:
   - condor

- include_tasks: cvmfs_client.yml
  when: galaxy_extras_config_cvmfs | bool
  tags:
   - cvmfs

- include_tasks: rabbitmq.yml
  when: galaxy_extras_config_rabbitmq | bool
  tags:
   - rabbitmq

- include_tasks: redis.yml
  when: galaxy_extras_config_redis | bool
  tags:
   - redis

- include_tasks: flower.yml
  when: galaxy_extras_config_flower | bool
  tags:
   - flower

- include_tasks: tusd.yml
  when: galaxy_extras_config_tusd | bool
  tags:
   - tusd

- include_tasks: supervisor.yml
  when: galaxy_extras_config_supervisor | bool
  tags:
   - supervisor

- include_tasks: galaxy_scripts.yml
  when: galaxy_extras_config_scripts | bool
  tags:
   - scripts

- include_tasks: galaxy_job_conf.yml
  when: galaxy_extras_config_galaxy_job_conf | bool
  tags:
   - job_conf

- include_tasks: startup.yml
  when: galaxy_extras_config_startup | bool
  tags:
   - startup
