- name: Ensure redis server is installed.
  apt:
    state: "{{ galaxy_extras_apt_package_state }}"
    name: "redis-server"
  when: galaxy_extras_install_packages | bool

- name: "Install redis python package for galaxy"
  pip:
    name: "redis"
    virtualenv: "{{ galaxy_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    extra_args: --index-url https://wheels.galaxyproject.org/simple --extra-index-url https://pypi.python.org/simple
  become: True
  become_user: "{{ galaxy_user_name }}"

- name: Ensure Redis configuration file is correct
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    owner: redis
    group: redis
    mode: 0640

- name: Ensure redis server is running.
  service: "name=redis-server state=started enabled=yes"
