# Attempt to restart nginx (if nginx is running)
- name: nginx status
  shell: pgrep -x nginx
  register: nginx_status
  ignore_errors: true

- name: Restart Nginx
  command: /usr/sbin/nginx -s reload
  become: yes
  become_user: root
  when: nginx_status.rc == 0
